#ifndef C_SOCKET_PROGRAMMING_PRACTICE_MY_LIBRARY_COMMON_PORT_H
#define C_SOCKET_PROGRAMMING_PRACTICE_MY_LIBRARY_COMMON_PORT_H 1

// The common port for all projects.
#define MY_COMMON_PORT 12345
#define MY_COMMON_PORT_STR "12345"

#endif
